### PR TITLE
Don't set "baseUrl" to that of the tsconfig.base.json

### PR DESCRIPTION
**Pull request by Falven**
This makes Apollo GraphQL work :)

### CODE REVIEW

**Comment by Falven** [comment]
> This is awesome!
> 
> Thank you @Falven so much for taking the time to look into it.
> 
> Does it fix the #8 issue you've created?
> 
> 
> 
> Later today, I will double check that the tests are passing and everything works as expected and merge it if everything is good.

It does fix the issue!
An easy test is to generate the nxaxure/function, setup Apollo/server as mentioned in [the azure functions integration](https://www.npmjs.com/package/@as-integrations/azure-functions) and build the project with and without the `rootDir` entry and observe the output. Thanks again for making this plugin!

**Review by AlexPshul — APPROVED** [review]
It looks like you've found some code I've left behind after my initial testing.
Thank you for taking the time to have a look at the issue and fixing it. :)

**Comment by AlexPshul** [comment]
I'm planning to work on some more minor fixes during this week.
Once I'm done, I will release the new version that includes this fix.

**Comment by Falven** [comment]
Hey @AlexPshul, were you able to publish this fix?

**Comment by AlexPshul** [comment]
Not yet @Falven,
I'm in the middle of quite a large refactor.
I will release a version later today with the initial change in hopes it won't break any existing workflow.
I'll tag you here when it's done.

**Comment by AlexPshul** [comment]
@Falven,
Version is on the way. :)
Should be out in a minute or two.

**Pull request merged**
